// ACTIVITY
export const LIST_ACTIVITIES_REQUEST = 'LIST_ACTIVITIES_REQUEST'
export const LIST_ACTIVITIES_SUCCESS = 'LIST_ACTIVITIES_SUCCESS'
export const LIST_ACTIVITIES_FAILURE = 'LIST_ACTIVITIES_FAILURE'

export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST'
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS'
export const GET_ACTIVITY_FAILURE = 'GET_ACTIVITY_FAILURE'

export const ARCHIVE_ACTIVITY_REQUEST = 'ARCHIVE_ACTIVITY_REQUEST'
export const ARCHIVE_ACTIVITY_SUCCESS = 'ARCHIVE_ACTIVITY_SUCCESS'
export const ARCHIVE_ACTIVITY_FAILURE = 'ARCHIVE_ACTIVITY_FAILURE'
