// ACTIVITY
export const LIST_ACTIVITIES_REQUEST = 'LIST_ACTIVITIES_REQUEST'
export const LIST_ACTIVITIES_SUCCESS = 'LIST_ACTIVITIES_SUCCESS'
export const LIST_ACTIVITIES_FAILURE = 'LIST_ACTIVITIES_FAILURE'
